version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"

  build:
    commands:
      - echo "Deploying to ${WORKSPACE}"
      - cd "$CODEBUILD_SRC_DIR"
      - chmod -R +x ./scripts
      - ./scripts/terraform.sh

  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*'
